### ISSUE TITLE
Error: Source and destination must not be the same.

### ISSUE THREAD

**Issue by joelbarbosa** [diegohaz/generact#17]
I couldn't generate a new Component at the same folder.

**Comment by joelbarbosa** [comment]
But just to your information,
I tried doing it in a saga file, not in a component.

**Comment by felippenardi** [comment]
The error message here seems very specific, isn't it the case that this is a feature not a bug?

**Comment by joelbarbosa** [comment]
Now,  I think so.
Maybe the library no need this functionality because it's out of the scope.
The library is to work with components and note any other type.

**Comment by joelbarbosa** [comment]
I will close the issue, because it's out of the way.
