### ISSUE TITLE
Support for react native

### ISSUE THREAD

**Issue by Shhzdmrz** [diegohaz/generact#21]
Does it support react native project? I added the extension to my vs code and tried in react native project but it was not working not even creating the directory. I also tried with installing generact globally but no use.

**Comment by diegohaz** [comment]
It should work. Could you share how the files are structured in your project (folders, filenames etc.)?

**Comment by Shhzdmrz** [comment]
Trying to use Button code to replicate as another component.
├── src/                        
│   ├── Button/
│   ├── ──  index.js
│   ├── ──  styles.js
├──  App.js
FYI I am using Windows 10 and using VS Code v1.22.1

**Comment by diegohaz** [comment]
So this might be the same problem as #15

Will close this in favor of that.
