### ISSUE TITLE
Edit contents on .json files

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/generact#4]
[react-static-boilerplate](https://github.com/kriasoft/react-static-boilerplate) has a `package.json` inside component folder. We need to change that as well as we do with `.css`, `.js` etc.

**Comment by dmitrika** [comment]
Hey, I'm going to help you with this issue.

```
{
  "name": "Button",
  "version": "0.0.0",
  "private": true,
  "main": "./Button.js"
}
```

In this case we copy whole package.json content and change only `name` and `main` values?

**Comment by diegohaz** [comment]
@dmitrika I guess that just adding `json` to this line solves the issue: https://github.com/diegohaz/generact/blob/master/src/utils.js#L40

We should have a new fixture and test case on https://github.com/diegohaz/generact/tree/master/test to ensure that.

File contents are replaced by `replaceContents` here: https://github.com/diegohaz/generact/blob/master/src/utils.js#L60-L67

**Comment by dmitrika** [comment]
Upd. Thank you for intro, will dig it.
